import matplotlib.pyplot as plt
import numpy as np

def plot_graph(sim_data, data, len):
	x_axis = range(len)
	plt.plot(x_axis,sim_data.iloc[:len,1],c='red',label='Simulated')
	plt.plot(x_axis,data.iloc[:len,1],c='blue',label='Historical')
	plt.axvline(x=30, color='k', linestyle='--')
	plt.axvline(x=61, color='k', linestyle='--')
	plt.axvline(x=91, color='k', linestyle='--')
	plt.axvline(x=122, color='k', linestyle='--')
	plt.axvline(x=153, color='k', linestyle='--')
	plt.axvline(x=181, color='k', linestyle='--')
	plt.axvline(x=212, color='k', linestyle='--')
	plt.xlabel('Days')
	plt.ylabel('Active Detected Cases')
	plt.legend()
	plt.show()
	plt.clf()
	plt.plot(x_axis,sim_data.iloc[:len,3],c='red',label='Simulated')
	plt.plot(x_axis,data.iloc[:len,3],c='blue',label='Historical')
	plt.axvline(x=30, color='k', linestyle='--')
	plt.axvline(x=61, color='k', linestyle='--')
	plt.axvline(x=91, color='k', linestyle='--')
	plt.axvline(x=122, color='k', linestyle='--')
	plt.axvline(x=153, color='k', linestyle='--')
	plt.axvline(x=181, color='k', linestyle='--')
	plt.axvline(x=212, color='k', linestyle='--')
	plt.xlabel('Days')
	plt.ylabel('Recovered')
	plt.legend()
	plt.show()
	plt.clf()
	plt.plot(x_axis,sim_data.iloc[:len,0],c='red',label='Simulated')
	plt.plot(x_axis,data.iloc[:len,0],c='blue',label='Historical')
	plt.axvline(x=30, color='k', linestyle='--')
	plt.axvline(x=61, color='k', linestyle='--')
	plt.axvline(x=91, color='k', linestyle='--')
	plt.axvline(x=122, color='k', linestyle='--')
	plt.axvline(x=153, color='k', linestyle='--')
	plt.axvline(x=181, color='k', linestyle='--')
	plt.axvline(x=212, color='k', linestyle='--')
	plt.xlabel('Days')
	plt.ylabel('Deaths')
	plt.legend()
	plt.show()
	plt.clf()
	plt.plot(x_axis,sim_data.iloc[:len,2],c='red',label='Simulated')
	plt.plot(x_axis,data.iloc[:len,2],c='blue',label='Historical')
	plt.axvline(x=30, color='k', linestyle='--')
	plt.axvline(x=61, color='k', linestyle='--')
	plt.axvline(x=91, color='k', linestyle='--')
	plt.axvline(x=122, color='k', linestyle='--')
	plt.axvline(x=153, color='k', linestyle='--')
	plt.axvline(x=181, color='k', linestyle='--')
	plt.axvline(x=212, color='k', linestyle='--')
	plt.xlabel('Days')
	plt.ylabel('Critical Patients')
	plt.legend()
	plt.show()
